org: sempejunior
app: heroes
service: heroes
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true`
  environment:
    DYNAMODB_TABLE: Heroes
  #configurações de permição no arquivo
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb: GetItem
        - dynamodb: UpdateItem
        - dynamodb: PutItem
      # Self para dizer que é o contexto do serverless, 
      # self.provider.region: Pegando a região configurada para a AWS pelo usuário
      # self:provider.enviroment: Pegando as variáveis do environment
      Resource: "arn:aws:dynamodb:${provider.region}:*:table/${provider.environment.DYNAMODB_TABLE}"

#Resources serve para quando subir o serverless, sejam criados os recursos que você precisa e configurou neste arquivo.
resources:
  Resources:
    HeroesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: nome
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: nome
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1 
functions:
  heroes: 
    handler: index.heroesInsert
    events:
      - httpApi:
          path: /heroes
          method: post
